chatCooldownSeconds: 0.5
defaultGameMode: world
plugins:
  titleInfo:
    updateSeconds: 4
  logs:
    webhookEnabled: true
    webhookPath: '/api/webhooks/xxxxx/xxxxxxxxxx'
modes:
  myMode:
    coolLink: 'My awesome link: google.com'
    