declare enum BodyPart {
    Pelvis = 0,
    Stomach = 1,
    Torso = 2,
    Head = 3,
    LeftShoulder = 4,
    LeftForearm = 5,
    LeftHand = 6,
    RightShoulder = 7,
    RightForearm = 8,
    RightHand = 9,
    LeftThigh = 10,
    LeftShin = 11,
    LeftFoot = 12,
    RightThigh = 13,
    RightShin = 14,
    RightFoot = 15,
}