declare enum MenuTab {
  Nothing = 0,
  EnterCity = 1,
  Lobby = 2,
  EmptyBase = 3,
  WorldCarShop = 9,
  WorldGunStore = 10,
  BurgerShop = 10,
  ClothingStore = 10,
  WorldStore = 11,
  WorldBank = 12,
  RoundCorporationWeapons = 14,
  RoundCorporationAmmo = 15,
  RoundCorporationEquipment = 16,
  RoundCorporationVehicle = 17,
  RoundCorporationStock = 18,
  WorldEmptyCorporation = 19,
  WorldCorporationApplication = 20,
  WorldCorporationHiring = 22,
  WorldCorporationFiring = 23,
  WorldCorporationTeam = 24,
  WorldCorporationRequisition = 25,
}
