declare enum VehicleName {
    TownCar = "Town Car",
    TownCar2 = "Town Car 2",
    Metro = "Metro",
    Limo = "Limo",
    Turbo = "Turbo",
    TurboS = "Turbo S",
    Beamer = "Beamer",
    Van = "Van",
    Van2 = "Van2",
    Minivan = "Minivan",
    Truck = "Truck",
    Trailer = "Trailer",
    Helicopter = "Helicopter",
    Train = "Train",
    NoclipCar = "",
    Hatchback = "Hatchback",
    Test = "Test", 
}